### ISSUE TITLE
add a favicon 

### ISSUE THREAD

**Issue by Chetana16032002** [Chetana16032002/E-commerce-website#1]
Add a favicon for this website make the favicon logo look creative using the website name(widehaven) or use this image
![Black   White Aesthetic Minimalist Signature Logo](https://user-images.githubusercontent.com/91176005/146501588-cba3d992-c309-4a64-9618-ca9ff07bea0d.png)

 
![Black   White Aesthetic Minimalist Signature Logo (1)](https://user-images.githubusercontent.com/91176005/146517856-12bdc953-9801-4b70-8c69-29a36ba2dc04.png)

**Comment by npkeerthi** [comment]
@Chetana16032002  Mam can you assign this to me 😂
